### ISSUE TITLE
rice crashes when X11 server connection is interrupted

### ISSUE THREAD

**Issue by klmr** [randy3k/rice#35] opened 2018-02-22 13:57 UTC
I’m running rice on a server inside a tmux session. I can display plots on my local computer via X11. However, when the X11 connection is killed (because the SSH connection closes) and I subsequently re-connect to the server and my `tmux` session, rice has been killed — and in addition my terminal misbehaves (which can be fixed by typing `reset`).

R, by contrast, merely gives the following error message:

> Error: X11 fatal IO error: please save work and shut down R

In addition, its `dev.list()` still lists the now-defunct `X11cairo` device. Closing that device and opening a new one works.

Here’s a step-by-step list of commands to reproduce this:

1. `local ⟩ ssh ‹some-remote-host›`
2. `remote⟩ tmux new`
3. <code>tmux&nbsp;&nbsp;⟩ rice</code>
4. <code>rice&nbsp;&nbsp;⟩ dev.new()</code>
5. Close the SSH session
6. `local ⟩ ssh ‹some-remote-host›`
7. `remote⟩ tmux attach`

Result: rice has crashed with the error message shown above.

**Comment by randy3k** [comment] 2018-02-22 16:55
There is actually a simpler way to reproduce it. Just open rice locally and execute `x11()`. Closing the x11 window will exit `rice` too.

**Closed** 2018-02-22 20:30 UTC

**Comment by randy3k** [comment] 2018-02-22 20:31
@klmr
78cedf3 will make sure that rice will stay alive if an error is occurred, however, it is still recommended for you to restart the application since there may be potential memory leaks.

**Comment by klmr** [comment] 2018-02-23 10:40
Cool, thanks a lot for the quick response, Randy.

Small quibble, while this indeed prevents rtichoke (love the new name!) from crashing immediately, it appears to mess up not only rtichoke itself but also the underlying shell:

1. When, after reattaching, I immediately quit rtichoke, the Bash I’m running doesn’t echo typed characters until I `reset` it.
2. Worse: if, instead of quitting, I try to plot something else this fails (OK). If I then subsequently try to quit rtichoke, it hangs indefinitely (sometimes the plotting itself already hangs … I can’t reproduce this reliably).

It would be nice if this could be handled more gracefully because it’s a very common workflow to have long-running interactive R sessions on a server (in particular in combination with Nvim-R) that users reattach to every day at work.

That said, it’s low priority, and the current state works fine for me (I reattach, save my data, quit and restart). If I find some time I might try to debug this myself and submit a PR.

**Comment by randy3k** [comment] 2018-02-23 13:30
It means my hack doesn’t reset all the internal states of the prompt. I will investigate it but do not guarantee if I would find a fix.

By the way, I don’t experience the shell being unresponsive. Though the cause is likely because the underlying tty is still in raw mode.

**Comment by randy3k** [comment] 2018-02-26 16:08
I can now actually reproduce the situation of the shell being unresponsive. But it occurs to both bare R and rtichoke. It makes me believe that it is an issue of R itself.
